---

- name: launch a compute instance
  hosts: localhost
  vars_files:
    - vars.yaml
  tasks:
  - name: Create volume
    os_volume:
      auth:
        auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"
        username: "{{ lookup('env', 'OS_USERNAME') }}"
        password: "{{ lookup('env', 'OS_PASSWORD') }}"
        project_name: "{{ lookup('env', 'OS_TENANT_NAME') }}"
      display_name: "{{ volname }}"
      size: "{{ volsize }}"
  - name: launch an instance
    os_server:
      name: "{{ volname }}"
      state: present
      auth:
        auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"
        username: "{{ lookup('env', 'OS_USERNAME') }}"
        password: "{{ lookup('env', 'OS_PASSWORD') }}"
        project_name: "{{ lookup('env', 'OS_TENANT_NAME') }}"
      image: "{{image}}"
      security_groups: "{{secgroups}}"
      flavor: "{{flavor}}"
      key_name: "{{key_name}}"
      nics:
        - net-name: "{{net_name}}"
      volumes:
        - "{{ volname }}"
      wait: yes
    register: osinstance

  - name: Wait 15 seconds
    pause: seconds=15
    when: osinstance.changed

  - name: Add new VM to ansible inventory
    add_host:
      name: imagebuilderansible
      ansible_host: "{{osinstance.server.public_v4}}"
      volume_device: "{{osinstance.server.volumes[0].device}}"
      ansible_become: True
      ansible_user: "{{ansible_user}}"
      ansible_sudo: true
      ansible_ssh_common_args: -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no

