---

- name: launch a compute instance
  hosts: localhost
  vars_files:
    - vars.yaml
  tasks:
  - name: ssh security group
    os_security_group:
      state: present
      name: ssh
      description: allow SSH access on port 22
  - name: add ssh rule
    os_security_group_rule:
      security_group: ssh
      protocol: tcp
      port_range_min: 22
      port_range_max: 22
      remote_ip_prefix: 0.0.0.0/0
  - name: Create volume
    os_volume:
      display_name: "{{ volname }}"
      size: "{{ volsize }}"
  - name: launch an instance
    os_server:
      name: "{{ vmname }}"
      state: present
      image: "{{ image }}"
      security_groups: ssh
      flavor: "{{ flavor }}"
      key_name: "{{ key_name }}"
      nics:
        - net-name: "{{ net_name }}"
      volumes:
        - "{{ volname }}"
      wait: yes
    register: osinstance

  - name: Wait 15 seconds
    pause: seconds=15
    when: osinstance.changed

  - name: Add new VM to ansible inventory
    add_host:
      name: imagebuilderansible
      ansible_host: "{{ osinstance.server.public_v4 }}"
      volume_device: "{{ osinstance.server.volumes[0].device }}"
      ansible_user: "{{ ansible_user }}"
      ansible_ssh_common_args: -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no

- name: Configure imagebuilder host
  vars:
    - WEB_ROOT: /usr/share/nginx/html
    - IMAGES_ROOT: "{{WEB_ROOT}}/images"
  hosts: imagebuilderansible
  tasks:
  - name: bashrc
    lineinfile: dest=/home/ubuntu/.bashrc line="export PATH=$PATH:/home/ubuntu/diskimage-builder/bin:/home/ubuntu/dib-utils/bin"
  - name: install packages
    become: True
    apt: name={{item}} update_cache=yes
    with_items:
      - expect
      - unattended-upgrades
      - git
      - qemu-utils
      - qemu
      - kpartx
      - ntp
      - debootstrap
      - nginx
      - screen
      - htop
      - python-pip
      - python-dev

  - name: pip upgrade
    become: True
    pip: name=pip state=latest

  - name: pip install python-keystoneclient
    become: True
    pip: name=python-keystoneclient

  - name: pip install python-glanceclient
    become: True
    pip: name=python-glanceclient

  - name: pip install networkx
    become: True
    pip: name=networkx

  - name: git clone dib-utils
    git: repo=https://github.com/openstack/dib-utils.git dest=/home/ubuntu/dib-utils force=yes

  - name: git clone SWITCH repo for diskimage-builder
    git: repo=https://github.com/switch-ch/diskimage-builder.git dest=/home/ubuntu/diskimage-builder force=yes version=SWITCHengines

  - name: Install diskimage-builder
    become: True
    shell: "cd /home/ubuntu/diskimage-builder ; python setup.py install"

  - name: Check if images folder exists
    stat: path='{{IMAGES_ROOT}}'
    register: images_folder

  - name: Format volume
    become: True
    filesystem: fstype=ext4 dev=/dev/vdb
    when: images_folder.stat.exists == False

  - name: Create web root for Nginx
    become: True
    file: path='{{IMAGES_ROOT}}' state=directory mode=0777

  - name: Manage fstab
    become: True
    mount: name='{{IMAGES_ROOT}}' src=/dev/vdb opts=nobootwait fstype=ext4 state=mounted
    when: images_folder.stat.exists == False

  - name: Create nginx config
    become: True
    template: src=templates/default.j2 dest=/etc/nginx/sites-available/default
    notify: restart nginx

  - name: Create distrosInfo file in home dir
    template: src=templates/distrosInfo.j2 dest=/home/ubuntu/distrosInfo

  - name: Load the create images bash script
    template: src=templates/SWITCHengines-create-images.sh.j2 dest=/home/ubuntu/SWITCHengines-create-images.sh mode="u=rwx,g=r,o=r"

  - name: Load the python upload utility for images
    copy: src=files/SWITCHengines-images-uploader.py dest=/home/ubuntu/SWITCHengines-images-uploader.py mode=0755

  - name: Load the python upload utility for images distrosInfo file
    copy: src=files/distrosInfo.py dest=/home/ubuntu/distrosInfo.py mode=0755

  handlers:
    - name: restart nginx
      become: True
      service: name=nginx state=restarted
